// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Students.Models;

namespace Students.Migrations
{
    [DbContext(typeof(StudentContext))]
    [Migration("20210214183241_AlterStudentData")]
    partial class AlterStudentData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Students.Models.Student", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Niveau")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("code")
                        .HasColumnType("varchar(25)");

                    b.Property<string>("fullname")
                        .IsRequired()
                        .HasColumnType("nvarchar(225)");

                    b.HasKey("id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Niveau = "4",
                            code = "A11",
                            fullname = "sara abboudi"
                        },
                        new
                        {
                            id = 2,
                            Niveau = "1",
                            code = "A22",
                            fullname = "Mohammed abboudi"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
